apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
    app: nginx
  name: ssl-certifies-front
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /etc/letsencrypt
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ssl-certifies
  labels:
    app: nginx
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: website
  name: website
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
        - image: gcr.io/authentic-idea-278120/github.com/limpioybueno/website
          imagePullPolicy: IfNotPresent
          name: website-1
      volumes:
        - name: v1
          persistentVolumeClaim:
            claimName: ssl-certifies
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: website
  name: website-hpa-4gqj
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: website
---
apiVersion: v1
kind: Service
metadata:
  finalizers:
    - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: website
  name: website-service
  namespace: default
spec:
  clusterIP: 10.12.5.79
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 30424
      name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - nodePort: 30425
      name: https
      port: 443
      protocol: TCP
      targetPort: 443
  selector:
    app: website
  sessionAffinity: None
  type: LoadBalancer
